#!/usr/bin/env python3
"""
Demonstration script for the LLM integration interface.

This script shows how to use the new LLM integration components:
- PlaceholderLLMProvider: Mock LLM for development/testing
- LLMIntegrationManager: Unified interface for LLM providers
- RAGService with LLM integration: Complete RAG pipeline

Usage:
    python llm_integration_demo.py
"""

import asyncio
import logging
from typing import Dict, Any

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Import our LLM integration components
from rag import (
    PlaceholderLLMProvider, 
    LLMIntegrationManager, 
    RAGService,
    BaseLLMProvider,
    LLMError
)


class CustomLLMProvider(BaseLLMProvider):
    """
    Example of a custom LLM provider implementation.
    
    This demonstrates how to create your own LLM provider
    that could integrate with services like OpenAI, Anthropic, etc.
    """
    
    def __init__(self, model_name: str = "custom-model-v1"):
        """
        Initialize the custom LLM provider.
        
        Args:
            model_name: Name of the custom model to use
        """
        self.model_name = model_name
        self.provider_name = "CustomLLM"
    
    async def generate_response(self, prompt: str, context: str, **kwargs) -> str:
        """Generate a custom response."""
        # Simulate some processing time
        await asyncio.sleep(0.1)
        
        # Create a more sophisticated response
        response_parts = [
            f"Based on the provided context, I can answer your question: '{prompt}'",
            "",
            "Key findings from the retrieved information:",
        ]
        
        # Extract some context preview
        if context and len(context.strip()) > 0:
            # Simple extraction of first few sentences
            sentences = context.replace('\n', ' ').split('. ')[:3]
            for i, sentence in enumerate(sentences, 1):
                if sentence.strip():
                    response_parts.append(f"{i}. {sentence.strip()}")
        
        response_parts.extend([
            "",
            f"This response was generated by {self.provider_name} using {self.model_name}.",
            f"Context length: {len(context)} characters",
            f"Sources analyzed: {kwargs.get('sources_count', 'unknown')}"
        ])
        
        return '\n'.join(response_parts)
    
    def get_provider_name(self) -> str:
        """Return the name of the LLM provider."""
        return self.provider_name
    
    def get_model_info(self) -> Dict[str, Any]:
        """Return information about the model being used."""
        return {
            "name": self.model_name,
            "type": "custom",
            "max_tokens": 2048,
            "temperature": 0.8,
            "provider": self.provider_name
        }


async def demo_placeholder_provider() -> None:
    """Demonstrate the PlaceholderLLMProvider."""
    print("\n" + "="*60)
    print("DEMO 1: PlaceholderLLMProvider")
    print("="*60)
    
    # Create placeholder provider
    provider = PlaceholderLLMProvider()
    
    print(f"Provider: {provider.get_provider_name()}")
    print(f"Model Info: {provider.get_model_info()}")
    
    # Generate a response
    response = await provider.generate_response(
        prompt="What is machine learning?",
        context="Machine learning is a subset of artificial intelligence (AI) that enables computers to learn and improve from experience without being explicitly programmed.",
        sources_count=2,
        context_length=150
    )
    
    print(f"\nGenerated Response:\n{response}")


async def demo_custom_provider() -> None:
    """Demonstrate a custom LLM provider."""
    print("\n" + "="*60)
    print("DEMO 2: CustomLLMProvider")
    print("="*60)
    
    # Create custom provider
    provider = CustomLLMProvider("advanced-model-v2")
    
    print(f"Provider: {provider.get_provider_name()}")
    print(f"Model Info: {provider.get_model_info()}")
    
    # Generate a response
    context = """
    Source 1: Machine learning is a method of data analysis that automates analytical model building.
    Source 2: It is a branch of artificial intelligence based on the idea that systems can learn from data.
    Source 3: Machine learning algorithms build mathematical models based on training data.
    """
    
    response = await provider.generate_response(
        prompt="How does machine learning work?",
        context=context,
        sources_count=3,
        context_length=len(context)
    )
    
    print(f"\nGenerated Response:\n{response}")


async def demo_llm_integration_manager() -> None:
    """Demonstrate the LLMIntegrationManager."""
    print("\n" + "="*60)
    print("DEMO 3: LLMIntegrationManager")
    print("="*60)
    
    # Create manager with default provider
    manager = LLMIntegrationManager()
    
    print("Initial Provider Info:")
    print(f"  {manager.get_provider_info()}")
    
    # Generate response with default provider
    result1 = await manager.generate_response(
        prompt="What is deep learning?",
        context="Deep learning is a subset of machine learning that uses neural networks with multiple layers.",
        config={"temperature": 0.5, "max_tokens": 500}
    )
    
    print(f"\nResponse with PlaceholderLLM:")
    print(f"  Provider: {result1['provider_name']}")
    print(f"  Response Length: {result1['response_length']} chars")
    print(f"  Config Used: {result1['config_used']}")
    
    # Switch to custom provider
    custom_provider = CustomLLMProvider()
    manager.set_provider(custom_provider)
    
    print(f"\nSwitched to: {manager.get_provider_info()['provider_name']}")
    
    # Generate response with custom provider
    result2 = await manager.generate_response(
        prompt="What is deep learning?",
        context="Deep learning is a subset of machine learning that uses neural networks with multiple layers.",
        config={"temperature": 0.7}
    )
    
    print(f"\nResponse with CustomLLM:")
    print(f"  Provider: {result2['provider_name']}")
    print(f"  Response Length: {result2['response_length']} chars")
    print(f"  Model: {result2['model_info']['name']}")


async def demo_rag_with_llm_integration() -> None:
    """Demonstrate RAG service with LLM integration."""
    print("\n" + "="*60)
    print("DEMO 4: RAG Service with LLM Integration")
    print("="*60)
    
    # Note: This demo shows the interface without actual search results
    # In a real scenario, you would have a working search service
    
    # Create LLM manager with custom provider
    custom_provider = CustomLLMProvider("rag-optimized-model")
    llm_manager = LLMIntegrationManager(custom_provider)
    
    # Create RAG service (without search service for demo)
    # In practice, you would pass a real VectorSearchService
    rag_service = RAGService(search_service=None, llm_manager=llm_manager)
    
    print(f"RAG Service LLM Provider: {rag_service.get_llm_provider_info()}")
    
    # Demonstrate provider switching
    placeholder_provider = PlaceholderLLMProvider("RAG-specific template: {prompt} | Sources: {sources_count}")
    rag_service.set_llm_provider(placeholder_provider)
    
    print(f"Switched to: {rag_service.get_llm_provider_info()['provider_name']}")
    
    # Configure LLM defaults
    rag_service.configure_llm_defaults({
        "temperature": 0.3,
        "max_tokens": 1500,
        "timeout": 45.0
    })
    
    print("Configured LLM defaults for RAG optimization")


async def demo_error_handling() -> None:
    """Demonstrate error handling in LLM integration."""
    print("\n" + "="*60)
    print("DEMO 5: Error Handling")
    print("="*60)
    
    class FailingLLMProvider(BaseLLMProvider):
        """Provider that always fails for testing error handling."""
        
        async def generate_response(self, prompt: str, context: str, **kwargs) -> str:
            """Generate a response that always fails for testing purposes."""
            raise Exception("Simulated LLM service failure")
        
        def get_provider_name(self) -> str:
            """Return the name of the failing LLM provider."""
            return "FailingLLM"
        
        def get_model_info(self) -> Dict[str, Any]:
            """Return information about the failing model."""
            return {"name": "failing-model", "type": "test"}
    
    # Test error handling
    failing_provider = FailingLLMProvider()
    manager = LLMIntegrationManager(failing_provider)
    
    try:
        await manager.generate_response("test", "context")
    except LLMError as e:
        print(f"Caught expected LLMError: {e}")
    
    print("Error handling working correctly!")


async def main() -> None:
    """Run all demonstrations."""
    print("LLM Integration Interface Demonstration")
    print("="*60)
    print("This demo shows the new LLM integration capabilities")
    print("that provide a flexible, extensible interface for")
    print("integrating various LLM providers with the RAG system.")
    
    try:
        await demo_placeholder_provider()
        await demo_custom_provider()
        await demo_llm_integration_manager()
        await demo_rag_with_llm_integration()
        await demo_error_handling()
        
        print("\n" + "="*60)
        print("SUMMARY")
        print("="*60)
        print("✅ PlaceholderLLMProvider: Ready for development/testing")
        print("✅ Custom LLM Providers: Easy to implement")
        print("✅ LLMIntegrationManager: Unified provider management")
        print("✅ RAG Integration: Seamless LLM integration in RAG pipeline")
        print("✅ Error Handling: Robust error management")
        print("\nThe LLM integration interface is ready for production use!")
        print("You can now easily integrate with OpenAI, Anthropic, or any other LLM service.")
        
    except Exception as e:
        logger.error(f"Demo failed: {e}", exc_info=True)
        print(f"\n❌ Demo failed: {e}")


if __name__ == "__main__":
    asyncio.run(main())